#!/usr/bin/env bash

# Architecture Check
check_v3="$(/lib/ld-linux-x86-64.so.2 --help | grep 'x86-64-v3 (supported, searched)' | awk '{print $1}')"
check_v4="$(/lib/ld-linux-x86-64.so.2 --help | grep 'x86-64-v4 (supported, searched)' | awk '{print $1}')"
script_dir="$(dirname -- "$(readlink -f -- "$0")")"
coolos_target="$(python3 "$script_dir/configure-coolos-repositories.py" --print-target)" || exit 1
python3 "$script_dir/configure-coolos-repositories.py" "$1" || exit 1

is_zen45() {
    [[ "$coolos_target" == znver4 ]]
}

if is_zen45; then
  sed -i '/^\[cachyos\]$/i \
[cachyos-znver4] \
Include = /etc/pacman.d/cachyos-v4-mirrorlist \
\
[cachyos-core-znver4] \
Include = /etc/pacman.d/cachyos-v4-mirrorlist \
\
[cachyos-extra-znver4] \
Include = /etc/pacman.d/cachyos-v4-mirrorlist\n' "$1"

  echo "znver4 or znver5 is supported (but we only have znver4 available)"
elif [ "$check_v4" == "x86-64-v4" ]; then
  sed -i '/^\[cachyos\]$/i \
[cachyos-v4] \
Include = /etc/pacman.d/cachyos-v4-mirrorlist \
\
[cachyos-extra-v4] \
Include = /etc/pacman.d/cachyos-v4-mirrorlist \
\
[cachyos-core-v4] \
Include = /etc/pacman.d/cachyos-v4-mirrorlist\n' "$1"

  echo "x86-64-v4 is supported"
elif [ "$check_v3" == "x86-64-v3" ]; then
  sed -i '/^\[cachyos\]$/i \
[cachyos-v3] \
Include = /etc/pacman.d/cachyos-v3-mirrorlist \
\
[cachyos-extra-v3] \
Include = /etc/pacman.d/cachyos-v3-mirrorlist \
\
[cachyos-core-v3] \
Include = /etc/pacman.d/cachyos-v3-mirrorlist\n' "$1"

  echo "x86-64-v3 is supported"
fi
